# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.base_response import BaseResponse
from openapi_server.models.one_ofobjectarray import OneOfobjectarray
from openapi_server.models.success_with_data_all_of import SuccessWithDataAllOf
from openapi_server import util

from openapi_server.models.base_response import BaseResponse  # noqa: E501
from openapi_server.models.one_ofobjectarray import OneOfobjectarray  # noqa: E501
from openapi_server.models.success_with_data_all_of import SuccessWithDataAllOf  # noqa: E501

class SuccessWithData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, data=None):  # noqa: E501
        """SuccessWithData - a model defined in OpenAPI

        :param code: The code of this SuccessWithData.  # noqa: E501
        :type code: str
        :param data: The data of this SuccessWithData.  # noqa: E501
        :type data: OneOfobjectarray
        """
        self.openapi_types = {
            'code': str,
            'data': OneOfobjectarray
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data'
        }

        self._code = code
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessWithData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessWithData of this SuccessWithData.  # noqa: E501
        :rtype: SuccessWithData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this SuccessWithData.


        :return: The code of this SuccessWithData.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this SuccessWithData.


        :param code: The code of this SuccessWithData.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def data(self):
        """Gets the data of this SuccessWithData.


        :return: The data of this SuccessWithData.
        :rtype: OneOfobjectarray
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SuccessWithData.


        :param data: The data of this SuccessWithData.
        :type data: OneOfobjectarray
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
