# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.one_ofobjectarray import OneOfobjectarray
from openapi_server import util

from openapi_server.models.one_ofobjectarray import OneOfobjectarray  # noqa: E501

class SuccessWithDataAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, data=None):  # noqa: E501
        """SuccessWithDataAllOf - a model defined in OpenAPI

        :param code: The code of this SuccessWithDataAllOf.  # noqa: E501
        :type code: str
        :param data: The data of this SuccessWithDataAllOf.  # noqa: E501
        :type data: OneOfobjectarray
        """
        self.openapi_types = {
            'code': str,
            'data': OneOfobjectarray
        }

        self.attribute_map = {
            'code': 'code',
            'data': 'data'
        }

        self._code = code
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessWithDataAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessWithData_allOf of this SuccessWithDataAllOf.  # noqa: E501
        :rtype: SuccessWithDataAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this SuccessWithDataAllOf.


        :return: The code of this SuccessWithDataAllOf.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this SuccessWithDataAllOf.


        :param code: The code of this SuccessWithDataAllOf.
        :type code: str
        """

        self._code = code

    @property
    def data(self):
        """Gets the data of this SuccessWithDataAllOf.


        :return: The data of this SuccessWithDataAllOf.
        :rtype: OneOfobjectarray
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SuccessWithDataAllOf.


        :param data: The data of this SuccessWithDataAllOf.
        :type data: OneOfobjectarray
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
